dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=sudoku
matrix:
  include:
  - env: TARGET=x86_64-pc-windows-gnu
    rust: nightly
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
before_install:
- set -e
- rustup self update
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: Ci4M8oPS5P5gsfA0ni9BKx7Ptwzn2xDEXIxCzuyoVctbYIxkA8W7vDq6uemTosvp6kGxi1Ge7aQ+LeNZFHtfXSOLpwfNYlfzqLunMNn63jDvRxg6cdbLbZHFFu+W9cSnhxPfSQa1PHQqvNQa56qPvS2Fw7l2K+ABQv/oBLAz9hChnhHXQJrlQEmhgip+AiWsfWh7xdE4Egntkz6h+/cxOS9vCnmshZApEhibz+FkQb42kiYeY/lSAUyOt3V2ElL34tP0ZqCymvI11RodoYXTCA/mrJueKfLlty11x5VKlha0JlhUf5hBsw9btgeB/sMSASguNLiK+vScSm+zXuXuMD3W3uWEDEDVBNO1nUTDQb3GlmOhaiaoIruHN3AlI5dVo29BG/RM0xRaV0INXdpFKRsb2md++e+5P30nDOdDMGXONqqRx+hM4g5Fvrl6V6NzXltPAXZRBlR8EG3QHDEwnztNMONJKtFiBWLWW1o7qbbUmh9ck+vPcKtgeO1fY+mFx7izLCCU/McvaGcUY3kg5nJck1FuzE0A9qMfrNJxow1wqYIPNm0RkXVyp77iPIZcArA3sJ2/WUi1h1bZr0U607oS0//2QRxRlnG14pBDEb2cDBFmOdmNX4WcL+BXOFY1WWKMr55lDrnc+1Z2J7Y2gy1oNDhWevqY31d/dWMSb/Y=
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    repo: Yiniau/sudoku
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
